# Generated by Django 3.2.3 on 2021-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
